// Eksport planu wierceń w formacie IREDES (DrillRig XML), zgodny strukturą z planem generowanym przez Strayos.
// Współrzędne: kolejność N, E, H (PointX = północ, PointY = wschód), metry; średnice w mm.

export function crc32(text) {
  let c, crc = 0xffffffff;
  const bytes = new TextEncoder().encode(text);
  for (const b of bytes) {
    c = (crc ^ b) & 0xff;
    for (let k = 0; k < 8; k++) c = c & 1 ? (c >>> 1) ^ 0xedb88320 : c >>> 1;
    crc = (crc >>> 8) ^ c;
  }
  return (crc ^ 0xffffffff) >>> 0;
}

const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[c]);
const f3 = (v) => v.toFixed(3);
const pad = (n) => String(n).padStart(2, '0');
export const isoNow = (d = new Date()) =>
  `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;

export function newPlanId() {
  const a = new Uint8Array(6);
  (globalThis.crypto ?? { getRandomValues: (x) => x.map(() => Math.random() * 256) }).getRandomValues(a);
  return [...a].map((b) => b.toString(16).padStart(2, '0')).join('');
}

// holes: [{ id, name, start: {n,e,z}, end: {n,e,z}, type, dia }]
export function buildIredesXml({ planId = newPlanId(), planName, project = '', comment = '', coordSystem = '', createDate = isoNow(), bearing = 0, workOrder = null, holes, checksum = true }) {
  const wo = workOrder ? `(${workOrder.lon.toFixed(8)},${workOrder.lat.toFixed(8)},${workOrder.alt.toFixed(8)})` : '';
  const head = (ind) => [
    `${ind}<IR:GenHead>`,
    `${ind}    <IR:FileCreateDate>${createDate}</IR:FileCreateDate>`,
    `${ind}    <IR:IRversion DownwCompat="V 1.0">V 1.0</IR:IRversion>`,
    `${ind}</IR:GenHead>`,
    `${ind}<IR:PlanId>${esc(planId)}</IR:PlanId>`,
    `${ind}<IR:PlanName>${esc(planName)}</IR:PlanName>`,
    `${ind}<IR:Comment>${esc(comment)}</IR:Comment>`,
    `${ind}<IR:Project>${esc(project)}</IR:Project>`,
    `${ind}<IR:WorkOrder>${wo}</IR:WorkOrder>`,
  ];
  const col = (x, y, z, w) => [
    '                    <IR:Col>',
    `                        <IR:x>${x}</IR:x>`, `                        <IR:y>${y}</IR:y>`,
    `                        <IR:z>${z}</IR:z>`, `                        <IR:w>${w}</IR:w>`,
    '                    </IR:Col>',
  ];
  const pt = (tag, p) => [
    `            <${tag}>`,
    `                <IR:PointX>${f3(p.n)}</IR:PointX>`,
    `                <IR:PointY>${f3(p.e)}</IR:PointY>`,
    `                <IR:PointZ>${f3(p.z)}</IR:PointZ>`,
    `            </${tag}>`,
  ];
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!--Borehole coordinates are in 'm'. Diameters are in 'mm'-->",
    `<!--Coordinates are in coordinate system ${esc(coordSystem)} (NEH order)-->`,
    '<!--Drillplan generated by Projekt wierceń strzałowych-->',
    '<DRPPlan xmlns="http://www.iredes.org/xml/DrillRig" xmlns:IR="http://www.iredes.org/xml" DRPPlanVersion="V 1.0" IRVersion="V 1.0" IRDownwCompat="V 1.0" DRPPlanDownwCompat="V 1.0">',
    ...head('    '),
    '    <DrillPosPlan IRVersion="V 1.0" IRDownwCompat="V 1.0">',
    ...head('        '),
    '        <PositionData>',
    '            <Coordsystem>',
    '                <IR:CoordSysName>local</IR:CoordSysName>',
    '                <IR:TMatrix>',
    ...col('1.000000', '0.000000', '0.000000', '0.000000'),
    ...col('0.000000', '1.000000', '0.000000', '0.000000'),
    ...col('0.000000', '0.000000', '1.000000', '0.000000'),
    ...col('0.000000', '0.000000', '0.000000', '1.000000'),
    '                </IR:TMatrix>',
    '                <IR:CsysType>L</IR:CsysType>',
    '            </Coordsystem>',
    '            <PlanIdRef></PlanIdRef>',
    `            <Bearing>${f3(bearing)}</Bearing>`,
    '        </PositionData>',
    '    </DrillPosPlan>',
    '    <DrillPlan>',
    `        <NumberOfHoles>${holes.length}</NumberOfHoles>`,
  ];
  for (const h of holes) {
    lines.push(
      '        <Hole>',
      `            <HoleId>${h.id}</HoleId>`,
      `            <HoleName>${esc(h.name)}</HoleName>`,
      ...pt('StartPoint', h.start).map((l) => l),
      ...pt('EndPoint', h.end),
      `            <TypeOfHole>${esc(h.type)}</TypeOfHole>`,
      `            <DrillBitDia>${Math.round(h.dia)}</DrillBitDia>`,
      '        </Hole>',
    );
  }
  lines.push('        <EquipmentData>', '            <OptionData/>', '        </EquipmentData>', '    </DrillPlan>');
  const body = lines.join('\n') + '\n';
  const trailer = [
    '    <IR:GenTrailer>',
    `        <IR:FileCloseDate>${createDate}</IR:FileCloseDate>`,
    ...(checksum ? [`        <IR:ChkSum>${crc32(body)}</IR:ChkSum>`] : []),
    '    </IR:GenTrailer>',
    '</DRPPlan>',
  ];
  return body + trailer.join('\n');
}
